title:          Aesi adapter for IntelliJ
email:          info@virtlink.com
author:         Daniel Pelsmaeker
description:    >
    An Aesi adapter for IntelliJ.
url:            "https://virtlink.com/aesi-intellij"

theme:          jekyll-theme-slate
show_downloads: true


